name = "nav-item"
pages_build_output_dir = "web/dist"

[[d1_databases]]
binding = "DB"
database_name = "nav_db"
database_id = "6d21c18c-e2aa-4842-a6c5-850745e09a6a"

[vars]
JWT_SECRET = "your_jwt_secret_key"
